on:
  - pull_request
  - push

name: build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}-${{ matrix.coverage }}

    env:
      extensions: curl, mbstring, openssl, pdo, pdo_sqlite
      SYMFONY_DEPRECATIONS_HELPER: weak

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ["5.6", "7.0", "7.1", "7.2"]
        coverage: [xdebug]
        experimental: [false]
        include:
          - os: ubuntu-latest            
            php: "7.3"
            coverage: pcov
            experimental: true
          - os: ubuntu-latest            
            php: "7.4"
            coverage: pcov
            experimental: true                   
          - os: ubuntu-latest            
            php: "8.0"
            coverage: pcov
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=-1, date.timezone='UTC'
          coverage: ${{ matrix.coverage }}
          tools: composer:v2

      - name: Determine composer cache directory on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Determine composer cache directory on Windows
        if: matrix.os == 'windows-latest'
        run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Update composer
        run: composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Composer install
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests PHP 5.6, 7.0, 7.1, 7.3, 8.0
        if: matrix.php != '7.2' || matrix.php != '7.4'
        run: |
          php -S 127.0.0.1:8000 -t tests/data/app >/dev/null 2>&1 &
          php codecept build
          php codecept run cli,unit

      - name: Run tests PHP 7.2, 7.4
        if: matrix.php == '7.2' || matrix.php == '7.4'
        run: |
          php -S 127.0.0.1:8000 -t tests/data/app -d pcov.directory=$(pwd)/tests/data/app >/dev/null 2>&1 &
          php codecept build
          php codecept run cli,unit,coverage --env COVERAGE=1